find_my_device_app/application/config/routes.rb
Rails.application.routes.draw do
  root 'static#index'

  resources :devices

  get 'home/:user', to: 'static#index'

  #login
  post 'login', to: 'users#login'
  get 'login', to: 'users#login'
  get 'login/submit', to: 'users#submit_login'
  post 'login/submit', to: 'users#submit_login'

  post 'authenticate', to: 'authentication#authenticate'

  get 'user/:id', to: 'users#show'

  #logout
  get 'logout', to: 'users#logout'

  #create user
  get 'create_user', to: 'users#create'
  post 'create_user/submit', to: 'users#submit_create'

  #unused
  post 'new_device/register', to: 'devices#build_partial_registration'
  post 'device/:device_id/set_status', to: 'devices#set_device_status'

  get 'redirect_to_documentation', to: 'static#redirect_to_documentation'
  get 'redirect_to_android_documentation', to: 'static#redirect_to_android_documentation'

  #private
  namespace :api, defaults: { format: 'json'} do 
    namespace :v1 do
      get 'user/:id', to: 'users#user'

      post 'new_device/create', to: 'devices#create'
      patch 'device/:device_id/set_status', to: 'devices#set_device_status'
      delete 'remove_device/:device_id', to: 'devices#delete_device'

      post 'register' => 'devices#register_device'
      post 'check_status' => 'devices#check_device_status'
      get 'device_types', to: 'devices#list_device_types'

      post 'device_type/create', to: 'devices#add_device_type'
    end
  end
end

find_my_device_app/application/app/models/user.rb
class User < ApplicationRecord
  has_many :devices
  has_secure_password

  # before_save :encrypt_password
  # after_save :clear_password

  # def encrypt_password
  #   if password.present?
  #     self.salt = BCrypt::Engine.generate_salt
  #     self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
  #   end
  # end
  # def clear_password
  #   self.password = nil
  # end

  def as_json(options = {})
    super(options.merge({ except: %i[password password_digest] }))
  end
end

find_my_device_app/application/app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
    before_action :authenticate_user, except: [:login, :create]

    def user 
        if current_user.id == params[:id]
            render json: {
              user_id: current_user.id,
              user_email: current_user.email
            }, status: 201
          else
            # Route to login
            render json: {
              message: "You do not have access to this account!"
            }, status: :forbidden
          end
    end

    def create
      email, password = params.values_at :email, :password
      if (!User.find_by_email(email))
        @new_user = User.new(:email => email, :password => password)
        @new_user.save
        render json: {
          user_id: @new_user.id,
          user_email: @new_user.email,
          access_token: token_manager.build(@new_user.id) 
        }, status: 201
      else
        render json: {
          message: "user already exists."
        }, status: :forbidden
      end
    end

    def login
      email, password = params.values_at :email, :password
      if (user = User.find_by_email(email)&.authenticate(password))
        render json: {
          user_id: user.id,
          user_email: user.email,
          access_token: token_manager.build(user.id)
        }, status: 201
      else
        render 'users/credentials_error', status: :unauthorized
      end
    end
end

find_my_device_app/application/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, except: [:login, :create, :submit_login, :submit_create, :logout]

  def new
  end

  def create 
  end

  def all_users 
    @users = User.all
    render json: {
        message: @users
    }, status: 201
  end

  def submit_create
    first_name, last_name, email, username, password, confirm_password = params.values_at :first_name, :last_name, :email, :username, :password, :confirm_password

    first_name = ActionController::Base.helpers.sanitize(first_name)
    last_name = ActionController::Base.helpers.sanitize(last_name)
    username = ActionController::Base.helpers.sanitize(username)
    confirm_password = ActionController::Base.helpers.sanitize(confirm_password)
    email = ActionController::Base.helpers.sanitize(email)
    password = ActionController::Base.helpers.sanitize(password)

    if (!User.find_by_email(email))
      @new_user = User.new(:first_name => first_name, :last_name => last_name, :email => email, :username => username, :password => password)
      @new_user.save
      token = token_manager.generate_token(@new_user.id)
      cookies.signed['X-Access-Token'] = {value:  token, httponly: true, expires: 2.hour.from_now}
      redirect_to action: 'show', id: @new_user.id
    else
      render json: {
        message: "user already exists."
      }, status: :forbidden
    end
  end

  def login
  end

  def logout
    current_user = nil
    cookies.signed['X-Access-Token'] = {value:  "", httponly: true}
    redirect_to root_path
  end

  def submit_login
    email, password = params.values_at :email, :password

    email = ActionController::Base.helpers.sanitize(email)
    password = ActionController::Base.helpers.sanitize(password)

    if (user = User.find_by_email(email)&.authenticate(password))
      token = token_manager.generate_token(user.id)
      cookies.signed['X-Access-Token'] = {value:  token, httponly: true, expires: 2.hour.from_now}
    
      redirect_to action: 'show', id: user.id
    else
      render 'users/credentials_error', status: :unauthorized
    end
  end

  def map_devices(devices)
    @mapped_devices = []
    devices.each do |device|
      device_object = device
      device_type = DeviceType.find_by_id(device.device_type_id)
      if (device_type != nil)
        device_object["type_name"] = device_type.name
        device_object["type_photo_url"] = device_type.photo_url
      else
        unkown_device = DeviceType.find_by_id("1")
        device_object["type_name"] = unkown_device.name
        device_object["type_photo_url"] = unkown_device.photo_url
      end
      @mapped_devices << device_object
    end
    return @mapped_devices
  end

  def show
    if current_user != nil && current_user.id == params[:id]
      @user = User.find_by_id(params[:id])
      @devices = map_devices(Device.where(:user_id => @user.id))
      @device_types = DeviceType.all

    else
      render 'users/login', status: :unauthorized
    end
  end
end

find_my_device_app/application/app/views/users/create.html.erb
<html style="height: 100%;">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Device Finder</title>
</head>

<body style="min-height: 100%; height: 100vh;">
  
    <div class="row" style="background-color: #FF5252; color: #FFFFFF; padding: 15px; padding-left: 30px; display: flex; flex-direction: row; position: absoloute;">
        <h1 class="display-1">Device Finder</h1>
    </div>

    <div style="background-color: #B2EBF2; padding: 15px; padding-left: 30px; height: 80%; text-align : center;">
    <div >
    <form id="CreateAccount" action="/create_user/submit" method="post">
    <div class="form-group">
      <%= label_tag(:first_name, "First Name") %>
        <%= text_field_tag(:first_name) %>
    </div>
    <div class="form-group">
      <%= label_tag(:last_name, "Last Name") %>
        <%= text_field_tag(:last_name) %>
    </div>
    <div class="form-group">
      <%= label_tag(:email, "Email") %>
        <%= text_field_tag(:email) %>
    </div>
    <div class="form-group">
      <%= label_tag(:username, "User Name") %>
        <%= text_field_tag(:username) %>
    </div>
    <div class="form-group">
      <%= label_tag(:password, "Password") %>
      <%= password_field_tag(:password) %>
    </div>
    <div class="form-group">
      <%= label_tag(:confirm_password, "Confirm Password") %>
        <%= password_field_tag(:confirm_password) %>
    </div>
    <button type="submit" class="btn btn-primary">Create Account</button>
  </form>
  <%= link_to 'Already have an account?', login_path() %>
    </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

find_my_device_app/application/app/views/users/credentials_error.html.erb
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Device Finder</title>
</head>

<body class="p-3 mb-2 bg-info text-white">
  <div class="container">
    <div class="row">
      <div class="p-3 mb-2 bg-danger text-white">
        <h1 class="display-1">Device Finder</h1>
      </div>
    </div>

    <div class="row">
        <h2>Username or password is incorrect</h2>
    </div>
    <%= link_to 'Back to Login', login_path() %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

find_my_device_app/application/app/views/users/expired_session.html.erb
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Device Finder</title>
</head>

<body class="p-3 mb-2 bg-info text-white">
  <div class="container">
    <div class="row">
      <div class="p-3 mb-2 bg-danger text-white">
        <h1 class="display-1">Device Finder</h1>
      </div>
    </div>

    <div class="row">
        <h2>Your session is expired!</h2>
    </div>
    <%= link_to 'Go to Login', login_path() %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

find_my_device_app/application/app/views/users/login.html.erb
<html style="height: 100%;">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Device Finder</title>
</head>

<body style="min-height: 100%; height: 100vh;">
  
    <div class="row" style="background-color: #FF5252; color: #FFFFFF; padding: 15px; padding-left: 30px; display: flex; flex-direction: row; position: absoloute;">
        <h1 class="display-1">Device Finder</h1>
    </div>

    <div style="background-color: #B2EBF2; padding: 15px; padding-left: 30px; height: 80%; text-align : center;">
    <div >
      <form id="login" action="/login/submit" method="post" style="text-align : center;">
        <div class="form-group" style="">
          <%= label_tag(:email, "Email") %>
          <%= text_field_tag(:email)%>
        </div>
        <div class="form-group" style="">
          <%= label_tag(:password, "Password") %>
          <%= password_field_tag(:password) %>
        </div>
        <button type="submit" class="btn btn-primary" style="">Login</button>
      </form>
    </div>
    <%= link_to 'Dont have an account?', create_user_path() %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

find_my_device_app/application/app/views/users/show.html.erb
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Device Finder</title>
</head>

<body class="">
<div class="horizontalLayout" style="background-color:#0097A7; font-family: Helvetica Neue,Helvetica,Arial,sans-serif; z-index: 5; position: relative; height: 10vh;">
    <h1 class="float_left" style="color:#FFFFFF; margin-top: 10px;">Device Finder</h1>
    <div style="padding-top: 15px; color: #FFFFFF; display: flex; flex-direction: row; align-items: center; position: absolute; right: 0; padding-right: 30px;">
        <%= button_to 'Logout', root_path, method: :get, class: 'btn btn-danger align-self-end' %>
    </div> 
    
</div> 

<%= javascript_pack_tag 'application' %>
<%= react_component("HomeProvider", {user: @user, devices: @devices, device_types: @device_types} ) %>
</body>
</html>